"""
Two-Tier Reasoning Engine

HRM-inspired hierarchical reasoning using Vertex AI Gemini 3 models:
- High-Level Tier: Gemini 3 Pro for abstract planning (thinking_level=high)
- Low-Level Tier: Gemini 3 Flash for rapid execution (thinking_level=low)

All processing stays on Vertex AI Global endpoint for commercial deployment.
"""

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

# Import Gemini client
try:
    from google import genai
    from google.genai import types
    GENAI_AVAILABLE = True
except ImportError:
    GENAI_AVAILABLE = False


@dataclass
class ReasoningStep:
    """A single step in the reasoning trace."""
    tier: str  # "high" or "low"
    action: str
    result: str
    tokens_used: int = 0
    latency_ms: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ReasoningPlan:
    """High-level plan generated by the strategic tier."""
    goal: str
    steps: List[str]
    constraints: List[str]
    success_criteria: str
    estimated_complexity: int  # 1-10


class TwoTierReasoner:
    """
    HRM-inspired two-tier reasoning engine on Vertex AI.

    High-Level Tier (Slow, Abstract):
    - Strategic planning and task decomposition
    - Uses Gemini 3 Pro with thinking_level="high"
    - Optimizes for accuracy over speed

    Low-Level Tier (Fast, Detailed):
    - Tactical execution and rapid responses
    - Uses Gemini 3 Flash with thinking_level="low"
    - Handles tool calls and quick decisions

    All models use global endpoint as required by Gemini 3.
    """

    # Gemini 3 model configuration - GLOBAL endpoint required
    HIGH_LEVEL_MODEL = "gemini-3-pro-preview"   # Pro for planning
    LOW_LEVEL_MODEL = "gemini-3-flash-preview"  # Flash for execution

    def __init__(
        self,
        project: Optional[str] = None,
        low_level_max_tokens: int = 2048
    ):
        self.project = project or os.getenv("GOOGLE_CLOUD_PROJECT") or "unk-app-480102"
        self.low_level_max_tokens = low_level_max_tokens

        self.reasoning_trace: List[ReasoningStep] = []
        self.current_plan: Optional[ReasoningPlan] = None

        # Initialize Vertex AI client with GLOBAL endpoint (required for Gemini 3)
        self.client = None
        if GENAI_AVAILABLE:
            try:
                self.client = genai.Client(
                    vertexai=True,
                    project=self.project,
                    location="global"  # REQUIRED for Gemini 3 models
                )
                print(
                    f"[TwoTierReasoner] Initialized on Vertex AI Global (Project: {self.project})")
            except Exception as e:
                print(f"[TwoTierReasoner] Init error: {e}")

    async def plan(self, goal: str, context: Optional[str] = None) -> ReasoningPlan:
        """
        High-level planning using Gemini Pro with thinking tokens.

        This is the "slow, abstract" tier for strategic decisions.
        """
        import time
        start_time = time.time()

        prompt = f"""You are a strategic planning system. Decompose this goal into actionable steps.

GOAL: {goal}

{f"CONTEXT: {context}" if context else ""}

Respond in this exact JSON format:
{{
    "goal": "restated goal",
    "steps": ["step 1", "step 2", ...],
    "constraints": ["constraint 1", ...],
    "success_criteria": "how to verify success",
    "estimated_complexity": 1-10
}}

Be thorough but concise. Focus on actionable steps."""

        if not self.client:
            # Fallback for no client
            return ReasoningPlan(
                goal=goal,
                steps=["Execute goal directly"],
                constraints=[],
                success_criteria="Goal completed",
                estimated_complexity=5
            )

        try:
            # Use Gemini 3 Pro with thinking_level="high" for deep reasoning
            # Note: Gemini 3 Pro only supports "low" and "high" thinking levels
            config = types.GenerateContentConfig(
                thinking_config=types.ThinkingConfig(
                    thinking_level="high",  # Maximum reasoning depth for planning
                    include_thoughts=True   # Get thought summaries for observability
                ),
                response_mime_type="application/json"
            )

            response = await self.client.aio.models.generate_content(
                model=self.HIGH_LEVEL_MODEL,
                contents=prompt,
                config=config
            )

            latency = (time.time() - start_time) * 1000

            # Parse response
            result = json.loads(response.text)
            plan = ReasoningPlan(
                goal=result.get("goal", goal),
                steps=result.get("steps", []),
                constraints=result.get("constraints", []),
                success_criteria=result.get("success_criteria", ""),
                estimated_complexity=result.get("estimated_complexity", 5)
            )

            # Track in reasoning trace
            self.reasoning_trace.append(ReasoningStep(
                tier="high",
                action=f"Plan: {goal[:50]}...",
                result=f"{len(plan.steps)} steps, complexity {plan.estimated_complexity}",
                latency_ms=latency
            ))

            self.current_plan = plan
            print(f"[HighTier] Generated plan with {len(plan.steps)} steps ({latency:.0f}ms)")
            return plan

        except Exception as e:
            print(f"[HighTier] Planning error: {e}")
            return ReasoningPlan(
                goal=goal,
                steps=["Execute goal directly"],
                constraints=[],
                success_criteria="Goal completed",
                estimated_complexity=5
            )

    async def execute(
        self,
        instruction: str,
        context: Optional[str] = None,
        system_instruction: Optional[str] = None
    ) -> str:
        """
        Low-level execution using Gemini Flash for speed.

        This is the "fast, detailed" tier for tactical operations.
        """
        import time
        start_time = time.time()

        prompt = instruction
        if context:
            prompt = f"Context: {context}\n\nTask: {instruction}"

        if not self.client:
            return "[No client configured]"

        try:
            # Use Gemini 3 Flash with thinking_level="low" for fast execution
            # "low" minimizes latency while still allowing some reasoning
            config = types.GenerateContentConfig(
                thinking_config=types.ThinkingConfig(
                    thinking_level="low"  # Minimize latency for tactical ops
                ),
                max_output_tokens=self.low_level_max_tokens
            )

            if system_instruction:
                config = types.GenerateContentConfig(
                    thinking_config=types.ThinkingConfig(
                        thinking_level="low"
                    ),
                    max_output_tokens=self.low_level_max_tokens,
                    system_instruction=system_instruction
                )

            response = await self.client.aio.models.generate_content(
                model=self.LOW_LEVEL_MODEL,
                contents=prompt,
                config=config
            )

            latency = (time.time() - start_time) * 1000
            result = response.text

            # Track in reasoning trace
            self.reasoning_trace.append(ReasoningStep(
                tier="low",
                action=f"Execute: {instruction[:50]}...",
                result=f"{len(result)} chars response",
                latency_ms=latency
            ))

            print(f"[LowTier] Executed in {latency:.0f}ms")
            return result

        except Exception as e:
            print(f"[LowTier] Execution error: {e}")
            return f"[Error: {e}]"

    async def reason(
        self,
        goal: str,
        context: Optional[str] = None,
        auto_execute: bool = False
    ) -> Tuple[ReasoningPlan, List[str]]:
        """
        Full two-tier reasoning: plan first, then optionally execute.

        Args:
            goal: The objective to accomplish
            context: Optional context information
            auto_execute: If True, execute all plan steps automatically

        Returns:
            Tuple of (plan, execution_results)
        """
        # High-level planning
        plan = await self.plan(goal, context)

        results = []

        if auto_execute:
            # Low-level execution of each step
            for i, step in enumerate(plan.steps):
                print(f"[Reasoning] Executing step {i+1}/{len(plan.steps)}: {step[:50]}...")
                result = await self.execute(
                    instruction=step,
                    context=f"Goal: {goal}\nStep {i+1} of {len(plan.steps)}"
                )
                results.append(result)

        return plan, results

    def get_reasoning_trace(self) -> List[ReasoningStep]:
        """Get the full reasoning trace for observability."""
        return self.reasoning_trace

    def get_tier_stats(self) -> Dict[str, Any]:
        """Get statistics for each reasoning tier."""
        high_steps = [s for s in self.reasoning_trace if s.tier == "high"]
        low_steps = [s for s in self.reasoning_trace if s.tier == "low"]

        return {
            "high_tier": {
                "count": len(high_steps),
                "avg_latency_ms": sum(s.latency_ms for s in high_steps) / max(len(high_steps), 1)
            },
            "low_tier": {
                "count": len(low_steps),
                "avg_latency_ms": sum(s.latency_ms for s in low_steps) / max(len(low_steps), 1)
            },
            "total_steps": len(self.reasoning_trace)
        }

    def clear_trace(self):
        """Clear the reasoning trace."""
        self.reasoning_trace = []
        self.current_plan = None
